package bsp

// LumpResolver Return an instance of a Lump for a given offset.
type LumpResolver func(id LumpId, header Header) (Lump, error)

// DefaultLumpOrdering is Source Engines default export order (at least it's an order specified in the original SDK).
// Source compile tools write lumps out of order, so while the ordering doesn't actually matter, it may be
// useful/more performant to maintain the same order, particularly post-export.
var DefaultLumpOrdering = [64]LumpId{
	LumpPlanes,
	LumpLeafs,
	LumpLeafAmbientLighting,
	LumpLeafAmbientIndex,
	LumpLeafAmbientIndexHDR,
	LumpLeafAmbientLightingHDR,
	LumpVertexes,
	LumpNodes,
	LumpTexInfo,
	LumpTexData,
	LumpDispInfo,
	LumpDispVerts,
	LumpDispTris,
	LumpDispLightmapSamplePositions,
	LumpFaceMacroTextureInfo,
	LumpPrimitives,
	LumpPrimVerts,
	LumpPrimIndices,
	LumpFaces,
	LumpFacesHDR,
	LumpFaceIds,
	LumpOriginalFaces,
	LumpBrushes,
	LumpBrushSides,
	LumpLeafFaces,
	LumpLeafBrushes,
	LumpSurfEdges,
	LumpEdges,
	LumpModels,
	LumpAreas,
	LumpAreaPortals,
	LumpLighting,
	LumpLightingHDR,
	LumpVisibility,
	LumpEntities,
	LumpWorldLights,
	LumpWorldLightsHDR,
	LumpLeafWaterData,
	LumpOcclusion,
	LumpMapFlags,
	LumpPortals,
	LumpClusters,
	LumpPortalVerts,
	LumpClusterPortals,
	LumpClipPortalVerts,
	LumpCubemaps,
	LumpTexDataStringData,
	LumpTexDataStringTable,
	LumpOverlays,
	LumpWaterOverlays,
	LumpOverlayFades,
	LumpPhysCollide,
	LumpPhysDisp,
	LumpVertNormals,
	LumpVertNormalIndices,
	LumpLeafMinDistToWater,
	LumpGame,
	LumpPakfile,
}
