name: Test and coverage
on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [main]
jobs:
  test:
    name: Run tests
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Install Go 1.19.0
        uses: actions/setup-go@v2
        with:
          go-version: '1.19.0'
      - name: Run coverage
        run: go test ./... -race -coverpkg=./libs/... -coverprofile=coverage.out -covermode=atomic
