name: Test and coverage
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    name: Run tests
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Install Go 1.19.0
        uses: actions/setup-go@v2
        with:
          go-version: '1.19.0'
      - name: Check gofmt on libs
        run: |
          unformatted_files=$(gofmt -l libs)
          if [[ -n "$unformatted_files" ]]; then
            echo "The following files are not properly formatted:"
            echo "$unformatted_files"
            echo "Run 'gofmt -w libs' to fix formatting."
            exit 1
          fi
      - name: Run coverage
        run: go test ./... -race -coverpkg=./libs/... -coverprofile=coverage.out -covermode=atomic
